[package]
name = "scop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.10.0"
glfw = "0.23.0"
glm = "0.2.3"
image = "0.25.1"
rand = "0.8.4"
